### PR TITLE
Update Madara.lua

### PR DESCRIPTION
**Pull request by ahmadi3d**
Fixed reset scans not fetching chapter name

### CODE REVIEW

**Comment by inkanime** [comment]
Hello, I tried the update, but the chapters do not appear in the list.

image

**Comment by ahmadi3d** [comment]
@inkanime This commit is fixing "https://reset-scans.com/" not the website you are trying to fetch.

**Comment by Slasar41** [comment]
I don't see any manga anymore in the website.

**Comment by ahmadi3d** [comment]
@Slasar41 This commit is a couple month old, The website URL has changed, I'll add a new commit for the new website URL later.

**Pull request closed without merging**
