### PR TITLE
Automatic the process of installing dependencies, minor fix for compiling with FPC stable

### PR DESCRIPTION
**Pull request by Kagamma**
This PR does 2 things:
- Minor fix to make FMD loads manga information when build with FPC stable version. This fix should not affect FPC trunk version.
- Automatic the process of installing 3rd party dependencies, by executing `install_submodules.bat`. This is mainly for newcomers who has a fresh install of Lazarus, without having to go through the hunt for packages on OPM + hopping around other github repos. This however does not include `laz.virtualtreeview`, this package still need to install manually via Lazarus's `Install/Uninstall Packages`. See #929 for `laz.virtualtreeview`.

`install_submodules.bat` requires `git` and `svn` to be installed on the system. Dependencies will be download to `3rd` directory. This should follows directory structure from the original FMD on sourceforge: https://sourceforge.net/p/fmd/code/HEAD/tree/trunk/3rd/

(Of course `install_submodules.bat` does nothing for those who already have a working environment)

### CODE REVIEW

**Comment by Slasar41** [comment]
Sorry, how to install `laz.virtualtreeview` and what to do with the file in issue 929?

And maybe move the batch file to `scripts` folder.
https://github.com/dazedcat19/FMD2/tree/master/scripts

**Comment by Kagamma** [comment]
That file is a patch/diff file (see See https://git-scm.com/docs/git-apply), you can apply it to local repo by using the command `git apply laz.virtualtreeview.patch` to test. 

`laz.virtualtreeview` is included with Lazarus, you can find and install it in package list the same way you install `onlinepackagemanager`:
image
Note that lazarus will also automatically prompt you to install it when it detects `laz.virtualtreeview` being used in project.

I will move the script to `scripts` directory.

**Comment by Slasar41** [comment]
Okay, looks like I managed to load them all.
image
And I can build it with FPC stable version too.
image
Manga info loaded fine.
image
~~But I can't see the forms in IDE.
image
Do you know why?~~
EDIT: It's working after applying your full patch.

Are there anymore change needed?

**Comment by Kagamma** [comment]
This PR is done and can be merged.

**Comment by Slasar41** [comment]
Thanks for the fix and the script.

**Comment by Slasar41** [comment]
Could you compile a library?
There's an issue regarding `libwebp.dll` for some users.

**Comment by Kagamma** [comment]
I am not at home right now and my laptop only has Arch Linux installed without a cross-build environment. It's pretty straightforward to compile though: https://developers.google.com/speed/webp/docs/compiling#compiling_on_windows_with_visual_c so anyone can do it.

**Pull request merged**
