### PR TITLE
ProjectTime: Fixed website support.

### LINKED ISSUE #616: [website module request] [bug-website module] VoidScans
**Website Information**
* **Name:** VoidScans
* **Root URL:** https://voidscans.net/
* **Directory list URL:** https://voidscans.net/manga

* **Example manga info URL:** https://voidscans.net/manga/series/Legend
* **Example chapter URL:** https://voidscans.net/manga/read/Legend/Chapter%2053

**Languages**
English

**Website relationship**
I think it's the new url of https://voidscans.com/

**Additional details**
Login and password are now required, but it's very easy to register a new account.
I think some limitations are present, maybe it will be safer to put limits on requests (like mangadex)

I used the template for the module request because of the url change and the login and password requirement.

### PR DESCRIPTION
**Pull request by Trollam**
resolves #616

### CODE REVIEW

**Comment by Slasar41** [comment]
ProjectTime should be in its own module instead of using `MangaShiro.lua` template.
As an example you can duplicate `ArangScans.lua` module as the base, rename it to `ProjectTime.lua`, then replace the lines with what you've already done.

**Comment by Trollam** [comment]
How do I know if a website should be in its own module or not ?

**Comment by Slasar41** [comment]
You need to familiarize with most websites that already supported on FMD.
Major templates are:
- FoOlSlide
- Genkan
- Lhscans
- Madara
- MangaKakalot
- MangaReaderOnline
- MangaShiro
- NineManga
- TruyenChon

After that when you want to add a website support, you'll recognize where should this website supposed to be added...
If you don't recognize the template at all, then it should be added to its own module.

**Comment by auraorb13** [comment]
Diem jancok

What the fuck

Pada tanggal Sen, 6 Sep 2021 01.37, Slasar41 ***@***.***>
menulis:

**Pull request merged**
