### PR TITLE
Update Madara.lua

### PR DESCRIPTION
**Pull request by bader515**
Changed mangalek from the old domain “https://mangalek.com” to the new one “https://lekmanga.net”

### CODE REVIEW

**Comment by Slasar41** [comment]
Please change it to use the new Madara template like this one: https://github.com/dazedcat19/FMD2/commit/a407e323e5a0a7308821a01f06d38fb21cee3052

**Comment by bader515** [comment]
Do you mean you’d like me to put it in a separate Lua file and import the Madara template there?
If so, I’m not very familiar with GitHub. Should I close this pull request, make the changes, and then open two separate pull requests for the files (madara.lua and mangalek.lua), or is there a way to make the changes within this pull request?

**Comment by Slasar41** [comment]
Do you use GitHub Desktop?

**Comment by bader515** [comment]
[Mangalek.zip](https://github.com/user-attachments/files/17608612/Mangalek.zip)
When I put it in a separate file, it managed to grab all the details about the manga except for two things, the chapters and the poster and I couldn't manage to get it working.
I know it's looking for "@id, "manga-chapters-holder"" which in this site's case would be replaced with "@class, "listing-chapters_wrap "" but it still doesn't work with this change implemented, tried to change some @id to @class but still the same issue present.

**Comment by bader515** [comment]
[Mangalek.zip](https://github.com/user-attachments/files/17609686/Mangalek.zip)
I got it working with this domain "lekmanga.org" but everything seems fine until you try to download, then the the number of pages stay at 0 and the download fails shortly after

**Comment by Slasar41** [comment]
What is the difference between .net and .org?

**Comment by bader515** [comment]
Nothing, but still, when I use the .net domain, it doesn't retrieve anything except the title, but with the.org domain, it grabs all the data except the chapter pages when downloading (it fails on 0).
This is an example of a page with the div element it's under:
```
<div class="page-break no-gaps">

		
            <img id="image-0" src="			
			https://tempscary.lekmanga.org/manga/arb1/data/manga_5ecd5c08d8c50ac1/6cc0295019eb4aec0126403c968727e5/image-01.png" daimante="">
			
			        </div>
```

**Comment by bader515** [comment]
They use madara-core-js version 6.4.5 if that's any help:
`<script type="text/javascript" src="https://lekmanga.org/wp-content/themes/orgmanga/js/core.js?ver=6.4.5" id="madara-core-js"></script>`

**Comment by Slasar41** [comment]
Change `function GetPageNumber()` to:
```lua
function GetPageNumber()
	local u = MaybeFillHost(MODULE.RootURL, URL)

	if not HTTP.GET(u) then return net_problem end

	CreateTXQuery(HTTP.Document).XPathStringAll('//div[contains(@class, "page-break")]/img/@src', TASK.PageLinks)

	return no_error
end
```

**Comment by bader515** [comment]
I created another pull request for it because some changes happened to the file yesterday, and it wasn't included in this version.

**Comment by Slasar41** [comment]
Actually it should still be fine even if there's already a change in the `Madara.lua` file. Try uploading `Mangalek.lua` to your patch-4 branch.

**Comment by bader515** [comment]
Done, and I'll close the other two pull requests since they are just duplicates

**Pull request merged**
