### PR TITLE
MangaPlus: Add Website Support

### LINKED ISSUE #17: [website module request] Shueisha MangaPlus
**Website Information**
* **Name:** Shueisha MangaPlus
* **Root URL:** https://mangaplus.shueisha.co.jp/
* **Directory list URL:** https://mangaplus.shueisha.co.jp/manga_list/all

* **Example manga info URL:** https://mangaplus.shueisha.co.jp/titles/100020
* **Example chapter URL:** https://mangaplus.shueisha.co.jp/viewer/1006657

**Additional context**
I saw that HaruNeko found a way to download chapters from MangaPlus.
maybe FMD can also duplicate the site access and download ?
https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/ShueishaMangaPlus.mjs

### PR DESCRIPTION
**Pull request by Inareous**
Additional: 
- Closes #17
- If you're on v2.0.30.0, `pb.dll` is not included by default so you'd have to download it manually and place it on fmd directory.

### CODE REVIEW

**Comment by JLChamberlain** [comment]
Did that but MangaPlus still isn't listed in available sources.

**Comment by Inareous** [comment]
Could you enable the log for FMD and upload it here?

**Comment by JLChamberlain** [comment]
> Could you enable the log for FMD and upload it here?

Log Attached
[fmd.log](https://github.com/dazedcat19/FMD2/files/6170569/fmd.log)

**Comment by Inareous** [comment]
Seems like I didn't properly cross compile the pb.dll against x64 arch. Should be easy fix.

**Comment by JLChamberlain** [comment]
> Seems like I didn't properly cross compile the pb.dll against x64 arch. Should be easy fix.

Okay. I'll wait for the changes and try again.

**Pull request merged**
