### PR TITLE
Update fmd.de.po

### PR DESCRIPTION
**Pull request by mezen**
Revisit some german translations and fixed some errors

### CODE REVIEW

**Comment by Slasar41** [comment]
If you can do it there's still some string not translated yet.
You can find it by searching `""`.

**Comment by mezen** [comment]
Ok, working on it.

Small question:
Has the word `Vacuum` in context of `Vacuum databases on exit` the same meaning like `Cleaning`? Or what does this option mean?

//Edit:
And another question: What is the meaning of that resourcestring?
```
#: tmainform.mnfiltergenreallindeterminate.caption
msgid "Indeterminate all"
msgstr "Indeterminate all"
```

**Comment by mezen** [comment]
Ok, that is the location of `Indeterminate all`. But, even after playing around, I have no clue what that option change. Except of setting the TriState of the checkboxes.

**Comment by Slasar41** [comment]
It's used to filter the manga list, `OR`.

**Comment by SDXC** [comment]
Because the checkboxes for the filters are static and always "set", we need this third state to let FMD know that it doesn't matter if that genre is in the filter results or not. If we uncheck all these genres we will exclude these genres instead.

"unbestimmt" would actually be the best direct translation for "indeterminate", but in case of that specific string it might make more sense to describe it as "Alle zurücksetzen".

**Comment by majora2007** [comment]
Vacuuming of a database means shrinking it. Basically after a lot of data has been added then deleted, the deleted rows aren't actually gone, they exist to be written over, so the file size of the database remains the same. 

A Vacuum actually removes these rows and thus the file size of the database shrinks.

**Comment by mezen** [comment]
@majora2007 I think my translation with "Bereinigen" seams to fit, it is a kind of clean up (of rows which are kind of marked as deleted)

I think I'm done with it then.

**Pull request merged**
