### PR TITLE
MangaGeko

### PR DESCRIPTION
**Pull request by xx255q**
Module for MangaGeko website

### CODE REVIEW

**Comment by Slasar41** [comment]
You forgot the extension file.

**Comment by xx255q** [comment]
I thought everything that was needed was under Files changed. How would you like it?

**Comment by Slasar41** [comment]
Add `.lua` to the file name.

**Review by Slasar41 — CHANGES_REQUESTED** [review]
Add `.lua` to the file name.

**Comment by xx255q** [comment]
This is a question about this, https://www.mangageko.com/ use to be Mreader I think, so should this module be added or that other one updated? #1192

**Comment by xx255q** [comment]
@Slasar41 what do you think

**Comment by Slasar41** [comment]
Oh, I thought this is for a new website.
Then we just need to change the URL in MReader module.

**Pull request closed without merging**
